.TH STRSLENREV 1
.SH NAME
strslenrev \- determine the length of a string in reverse
.SH SYNOPSIS
.B #include <libext.h>
[\fB\-n\fR \fIBITS\fR]
[\fB\-\-bits\fR \fIBITS\fR]
.IR file ...
.SH DESCRIPTION
.B strslenrev
calculate length of a string in reverse, calculation stops when a character of the string matches with any of the characters in the given set or the beginning of the string is reached.
.SH OPTIONS
.TP
.BR \-n ", " \-\-bits =\fIBITS\fR
Set the number of bits to modify.
Default is one bit.